### ISSUE TITLE
Add an icon/logo

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Chirp#26]
https://developer.gnome.org/hig/guidelines/app-icons.html

**Comment by Dianesaur** [comment]
Hi again, this is actually perfect since I have some experience with drawing so I would like to help! Is there any specific wants for the logo like a bird maybe? Or color palette?

**Comment by TheRustyPickle** [comment]
Hello, @Dianesaur! I appreciate your interest. I don't have any specific want or color palette for it however gnome apps usually follows the guideline in the issue description. You can take a look at it, the rest is up to your creativity and what you can come up with. If you want to work on it, let me know, and I'll assign you to it. Thank you!

**Comment by Dianesaur** [comment]
Ok, I definitely want to work on this please :D

**Comment by Dianesaur** [comment]
@TheRustyPickle Hi I did some concept desgins and I wonder which ones you like (if none of them works no worries I'll make news ones since they're only a sketch) Also i couldn't figure out the gnome app but I'll try to replicate their style/color and such 

![WIP_CHIRPMESSAGE](https://github.com/TheRustyPickle/Chirp/assets/119092992/30f29071-fb9e-4a7e-8924-312cd0e5d996)

**Comment by TheRustyPickle** [comment]
Thank you for your efforts, @Dianesaur! The first two looks good to me. By gnome guidelines, I meant that this project uses GTK4 and libadwaita which is under GNOME. GNOME has a [guideline](https://developer.gnome.org/hig/guidelines/app-icons.html) on how the app icon should be designed for GNOME apps and often prefers simple, geometric icons. Hope this helps. Thank you again!

**Comment by Dianesaur** [comment]
@TheRustyPickle  Here you go! It's in vector I can give you the illustrator file but you can resize it to whatever size you want
![Bird@10x](https://github.com/TheRustyPickle/Chirp/assets/119092992/cff3d986-9672-49e6-aebe-b3e0b6cb5a48)

**Comment by TheRustyPickle** [comment]
Hello, @Dianesaur! How are you doing? Thank you for your effort on this! Can you put the image in the project's root in preferably SVG format and open a PR so I can merge it? You can also put the image in the readme file, if not, I can do it later as well.

**Comment by TheRustyPickle** [comment]
Resolved on #86

**Comment by nguyenvuonghlnb** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
plotchy, @Nokhal, @thebor1337, @GaFeFi, @wuwe1, @hung-ngm, @hehui0316, @cometkim, @seanmrnda, @ygsgdbd, @omegablitz, @imterryyy, @dahlia, @WuTao18, @cpucorecore, @2020-io, @erwanor, @Leechael, @xlc, @rhnparlors, @insipx, @kris524, @hananbeer, @phohtoo, @wbogocki, @1755, @darrylyeo, @NoorahSmith, @xuyi33333, @liangyihuai, @june8036, @qymlyl, @en, @0xdapper, @DavidHur, @think-in-universe, @banyudu, @goncaloMagalhaes, @myiwen, @cryptoquick, @JesterGiroud, @jazzlost, @sleepyqadir, @hhamud, @LiangMa, @oantoro, @bernahe, @degatchi, @pandadefi, @foxytanukiaditya172926, @andrewgazelka, @wpank, @tylerdurden793, @vacekj, @red-0ne, @kioqq, @wuminzhe, @nmoroze, @stormcoder, @AlicanC, @bigsky77, @shadawck, @uniyalabhishek, @samlet, @DMClVG, @dragan-novakovic, @AllanM007, @pichtranst123, @zeusAlgo, @bjornwgnr, @dcb9, @penso, @vuvoth, @Farteen, @scorbajio, @pecpwee, @kobby-pentangeli, @bobnautic, @wadro, @0xbillw, @wellington1993, @orangemio, @bmwoolf, @mikedemarais, @amirgamil, @0xmovses, @monomadic, @jhscheer, @echoboss, @carlynf, @byeongjee, @atetc, @valipan, @ackintosh, @goalongway, @folowing, @rcavaz, @madnight, @zacck-zzZhangHanDong, @minj2me, @akannke, @asylumsbsa, @waheya, @Z-Zhijie, @delneg, @Renenes, @SebastianElvis, @mutalisk999, @enshrineHelium, @dineshpinto, @sgc109, @imloama, @ahmadkaouk, @jupiterstudio, @helderjnpinto, @gwpl, @Just4Ease, @LeoHoward, @bartekus, @hexrcs, @igaozp, @sigmachirality, @zsluedem, @arindas, @Ferret-san, @coolsnake, @AkiaCode, @akru, @Pantyhose-X, @wp-lai, @Lawliet-Chan, @ahmedali8, @mastercyb, @0ihsan, @kmlupreti, @mehmetegemen, @lastmjs, @0xYYY, @rodrigoherrerai, @jmingov, @xJonathanLEI, @chin0, @anylzer, @kubo39, @heshdotcc, @platinum3d, @EthSecurity1, @Animismo

**Comment by nguyenvuonghlnb** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
tedt10e, @willjleong, @tomasovic, @tocoteron, @brightclark, @yanganto, @Un4G173N, @g-r-a-n-t, @juniuszhou, @abel-byte, @LXJ2, @dav8t, @hustxiaoc, @daweth, @1701175145, @DaviRain-Su, @3b40eb98, @rahulnm, @masami87, @Dmdv, @Shawndslee, @Glow-in-the-dark, @Darth123658, @ZGQ-inc, @defispartan, @rofuun, @haua998, @Lz1y, @Dougie008, @TalkWIthKeyboard, @massun-onibakuchi, @jakerumbles, @hzqd, @longcpp, @alikonuk1, @steffenix, @stan-dot, @weipin, @19-xiaogao, @fanyang1988, @xiaosongfu, @dimlev, @Folyd, @mshrieve, @deadblackclover, @mdtanrikulu, @NukeManDan, @zeroXbrock, @3ddi, @chenjunwen186p0p3yee, @astrolemonade, @SergioArrighi, @archi-cszcli, @daiwanwei, @pedrommaiaa, @randhindi, @yihau, @andreisilviudragnea, @idkwim, @Godaiandi, @fuyutarow, @limotree, @intdance, @ccamateur, @coopbri, @macrocan, @yaroslavyaroslav, @DennisDv24, @nkysg, @iamazy, @b00f, @ZhiXiao-Lin, @zkmsg, @HAOYUatHZ, @lowlowcoder, @thasarito, @MRGRAVITY817, @caoanlong, @franssl, @ivanceras, @dalaorock, @ccmlm, @marko-lazic, @asadkovich, @Apoll95, @rameight, @sorawit, @misoobu, @MoodyBoi, @eratzlaff, @saki-osive, @DukeCaesar, @sashaaldrick, @tacoda, @greyireland, @frost-scorpio, @chirag-bgh, @bredamatt, @marmelo-cotoneumXsssTsssX, @Chisaaato, @fruitbox12, @takahiro-prog, @zkoranges, @t1anchen, @phamidko, @sondnm, @pistomat, @somerb, @lightclient, @scrogson, @fxsjy, @Anthler, @moreal, @tsirysndr, @tolgaisik, @s7v7nislands, @cryptonerdcn, @exdx, @bradamelton, @sayan011, @sbc64, @mratsim, @diop, @keepitsane, @taye-beckford, @FISHers6, @maschad, @KyrinCode, @nonsense, @xamgore, @martinloesethjensen, @nickdoherty, @Franceshe, @xxibcill, @svercl, @jameshoo7, @TomatoCream, @puzzithinker, @benrod3k, @vinhbhn, @Naokiakazawa, @stevekeol, @ZePedroResende, @minikin, @phial3, @oblique, @eikodev, @Bart200c

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
wiznard, @xeno097, @JBLarson, @cyjrun, @NiBlack114, @PwnSecc, @shanechen0916, @eartht0sarah, @gzb4219, @librity, @shreyasrk, @NaelShichida, @gamerey43, @Vicksyn, @pratamawijaya, @Mr-ONADASKY, @nayeem-17, @astrolemonade, @fcarli3, @vgjm, @ohenepee, @kaustav202, @udittyagi, @nikhilkumar5294, @chauvansang, @darkmatter11235, @MrJ89Carrazco, @imdongchen, @rapturev, @GUESSZERO4, @lifeifeixz, @lindsaytennie, @kdeepak99, @lucassantos94, @bharath-b06, @yizhilee, @wiready, @frankiefab100, @seanyu-git, @cenzwong, @bimap98, @ltchr, @grmpyninja, @llss6887, @9M6, @LeoCp, @Phoenixfan, @cycloss, @b1xt, @adotsloanwigust, @Ocelani, @ropital, @webgurucan, @Sunchao1996, @Bazinga09, @omerkhawaja, @Monem-Shahriar, @Spyder15, @karolgro, @prairitm, @jaeyongjaykim, @mexanix, @jkyochen, @Mrs-Shadows, @slai-fi, @xlaoy, @M-abobakr, @xiaozhiliaoo, @averias, @liuxuleigitpub, @prite36, @DionysusBenstein, @vittalkolla, @Zeb-blockchain, @Laili2, @dfxshxr, @qdmudong, @bmorelax, @vincent0426, @Ay-355, @jogunfuwa, @BhoopathiSaisagar, @arvryna, @diivi, @kwabenasapong, @LeoMoonStar, @GaleevDinar, @kristsokoli, @aksinha334, @iBerezkin, @banshee0716, @suyanlong, @fruizrob, @lhp3851, @chhk-dev, @123mpozzi, @huazhuangnan, @doc22940, @zhouzhuojielenny-mo, @SHUBHAM14111, @BhabeshMali, @chaosBreaking, @shouse, @baiyunping333, @pedropietro, @jackjm, @sush987, @bysr, @Korbin-Dallas, @qincloud, @Dvisacker, @muffafa, @p1yu5h0, @maxgfr, @znddzxx112, @farukEncoded, @isaccavalcante, @gubaijin, @dabai-cai, @Forensicxs, @mutalisk999, @unclebob2013, @Mhdi-kr, @arihantbansal, @gucmurat, @acromm, @reed-soul, @BhaktiRathod, @zhu2688, @SidharthArya, @87sam12, @DrRenardScD, @Yothgewalt, @KereChi, @therahulbhati, @akzala98, @AKMB-dev, @Medha08, @haoht, @chiorji, @cmaughan, @cannadayr, @nirmalhk7, @Qodestackr, @duktig666, @tuanna47, @kevinlv1024, @misterchenleiya

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zerosnacks, @lambda-0x, @llifezou, @vernonjohnson, @lightning-li, @micrub, @sebastiantf, @somerb, @kss-fluency, @whilei, @ZGQ-inc, @enif-lee, @earthflower, @WilfredTA, @Just4Ease, @haua998, @kootsZhin, @valeryz, @felixangell, @IvonaldoAmaral, @orangemio, @vbrvk, @execnow, @marko-lazic, @moreal, @brandawsd, @kimpers, @nuts-rice, @ZiNai, @sbusso, @pistomat, @dackerer, @garious, @hustxiaoc, @r-tom90, @kriptoibo, @dineshpinto, @saman-pasha, @dimlev, @TomaszWaszczyk, @trmaphi, @guijunchen, @Dmdv, @Jawy77, @qymlyl, @denismaxim0v, @0xbillw, @longcpp, @2Higara, @gabrielfalcaop4r4no1ak, @0xethsign, @sgc109, @puzzithinker, @goncaloMagalhaes, @zzir, @zqhxuyuan, @hyperleex, @BoundlessCarrot, @cherry-yl-sh, @Archisman-Mridha, @X4, @seyedhanaee, @p0p3yee, @jtriley-eth, @diazMelgarejo, @onlymaresia, @dcbuild3r, @Animismo, @jonahcui, @rhizome01, @joyqvq, @cd1m0, @TalkWIthKeyboard, @mmacedoeu, @zhangzhongzhong, @edmand46, @pinardZ, @tmpfs, @ImpossibleReality, @TheRustyPickle, @nellyisanon, @tommy-ca, @asadkovich, @zachperez, @alfellati, @willjleong, @Shawndslee, @marmelo-cotoneum, @hineso11, @wstreet, @sorpaas, @ackintosh, @mia-stein, @HegelXu, @HAOYUatHZ, @mcass19, @fwx5618177, @darrylyeo, @DieracDelta0xKaso, @vaniisgh, @lit0ne, @TomatoCream, @sbc64, @JesterGiroud, @billylindeman, @guim4dev, @wuanzhuan, @scrogson, @h3lio5, @ndeepak, @Richa-iitr, @royswale, @Glow-in-the-dark, @limotree, @Volland, @morimolymoly, @ygsgdbd, @This-Is-Prince, @rohitasb, @way2ex, @nanne007, @Keeeeeeeks, @markall93, @arthurmm-cloudwalk, @wadro, @Janmajayamall, @c0np4nn4, @olalonde, @piavgh, @skundu42, @esp10mm, @iwctwbai, @sekmet, @sing1ee, @1755, @ktmlm, @Niraj-Kamdar, @rahulsoshte2, @amirgamil, @Renenes, @tacoda, @VictorTaelin, @dOrgJelli, @timothyklim, @imloama, @mrxvt, @FutureInfinity, @armujahid
