### ISSUE TITLE
Add more sources of random images

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Chirp#46]
Currently following APIs are used

* Dicebear
* Robohash

Would be nice to have more sources of random images. The following needs to be updated

* Add a new function to generate a proper link to the new image source API on `utils.rs`
* `generate_random_avatar_link` should be updated with an option to call the new function.

**Comment by aybeedee** [comment]
Hi @TheRustyPickle, can I attempt to add [Multiavatar](https://api.multiavatar.com/)? I can also look for more if required.

**Comment by TheRustyPickle** [comment]
@aybeedee Sure, feel free to work on it.

**Comment by TheRustyPickle** [comment]
@aybeedee I have updated the description a bit with what needs to be done. Let me know if you have any questions, or confusion about something or need some help.
