### ISSUE TITLE
Limit user name to 250 chars

### ISSUE THREAD

**Issue by TheRustyPickle** [TheRustyPickle/Chirp#71]
Rough modifications needed for the issue:

* Modify `bind` and `edit_name` functions on `user_prompts.rs` to ensure names with over 250 chars don't get accepted
* If over 250, it should show an error text with the details, disable the confirm button, and add the error CSS to the entry  
* Perhaps the `bind` function should be separated for name and image editing for easier handling similar to `bind_int` for numbers

**Comment by Dianesaur** [comment]
I would like to contribute to this feature!

**Comment by TheRustyPickle** [comment]
@Dianesaur Thank you for your interest! Feel free to contribute to it. I have modified the description a bit to highlight what changes are needed to make it work. If you have any questions, confusion or need help with something, you can always ask here.

**Comment by Dianesaur** [comment]
@TheRustyPickle Hi I'm so sorry I have zero experience with coding and I thought I could be able to find a way to work on it through youtube and trial and error. But I realized that there's actual non code ways to contribute so I think I would like to give this someone who's more experienced? Or at least take me off the list of expecting to contribute? Again so sorry,

**Comment by TheRustyPickle** [comment]
@Dianesaur No problem, thanks for letting me know. For now, there is only #26 that is non-code. If you are interested, you can take a look otherwise good luck, hope you find the type of issues that you are looking for!
